-- Auto-generated by scripts/build_reference_data.py
PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

INSERT OR IGNORE INTO Countries (CountryId, Code, Name) VALUES
('COUNTRY_DEFAULT', 'WLD', 'World'),
('COUNTRY_BRAZIL', 'BRA', 'Brazil'),
('COUNTRY_CAMBODIA', 'CAM', 'Cambodia'),
('COUNTRY_CANADA', 'CAN', 'Canada'),
('COUNTRY_FRENCH_POLYNESIA', 'FRE', 'French Polynesia'),
('COUNTRY_JAPAN', 'JAP', 'Japan'),
('COUNTRY_SPAIN', 'SPA', 'Spain'),
('COUNTRY_UNITED_STATES', 'USA', 'United States');

COMMIT;
