-- Auto-generated by scripts/build_reference_data.py
PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS CountryAliases (
    AliasNorm TEXT PRIMARY KEY,
    CountryId TEXT NOT NULL,
    FOREIGN KEY (CountryId) REFERENCES Countries(CountryId)
);

INSERT OR IGNORE INTO CountryAliases (AliasNorm, CountryId) VALUES
('brazil', 'COUNTRY_BRAZIL'),
('cambodia', 'COUNTRY_CAMBODIA'),
('canada', 'COUNTRY_CANADA'),
('french polynesia', 'COUNTRY_FRENCH_POLYNESIA'),
('japan', 'COUNTRY_JAPAN'),
('spain', 'COUNTRY_SPAIN'),
('u s', 'COUNTRY_UNITED_STATES'),
('u s a', 'COUNTRY_UNITED_STATES'),
('united states', 'COUNTRY_UNITED_STATES'),
('united states of america', 'COUNTRY_UNITED_STATES'),
('usa', 'COUNTRY_UNITED_STATES');

COMMIT;
