-- ============================================================================
-- Seed CatchStyles reference data (idempotent)
-- ============================================================================

PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

INSERT OR IGNORE INTO CatchStyles (CatchStyleId, Name, Description, WrestlingPurity, EntertainmentFocus, HardcoreIntensity, LuchaInfluence, StrongStyleInfluence, FanExpectationMatchQuality, FanExpectationStorylines, FanExpectationPromos, FanExpectationSpectacle, MatchRatingMultiplier, PromoRatingMultiplier, IconName, AccentColor, IsActive) VALUES
('STYLE_PURE_WRESTLING',
 'Pure Wrestling',
 'Focus absolu sur la qualité technique des matchs. Workrate élevé, compétition sportive, peu de storylines extravagantes.',
 90,
 20,
 0,
 10,
 30,
 90,
 30,
 20,
 20,
 1.3,
 0.7,
 '🥋',
 '#4CAF50',
 1),
('STYLE_SPORTS_ENTERTAINMENT',
 'Sports Entertainment',
 'Équilibre entre wrestling et spectacle. Storylines complexes, gimmicks marquants, grande production.',
 50,
 80,
 20,
 15,
 10,
 60,
 80,
 70,
 85,
 1.0,
 1.2,
 '🎭',
 '#2196F3',
 1),
('STYLE_HARDCORE',
 'Hardcore Wrestling',
 'Violence extrême, objets, sang, no-DQ. Public niche amateur de brutalité et spots dangereux.',
 30,
 40,
 95,
 0,
 20,
 50,
 40,
 30,
 80,
 1.1,
 0.8,
 '💀',
 '#F44336',
 1),
('STYLE_LUCHA_LIBRE',
 'Lucha Libre',
 'High-flying, rythme rapide, masques, trios. Tradition mexicaine avec acrobaties spectaculaires.',
 60,
 60,
 10,
 95,
 0,
 75,
 50,
 40,
 80,
 1.2,
 0.9,
 '🎪',
 '#FF9800',
 1),
('STYLE_STRONG_STYLE',
 'Strong Style',
 'Dureté japonaise, stiff strikes, fighting spirit. Présentation sérieuse et sportive.',
 85,
 30,
 30,
 5,
 95,
 85,
 40,
 25,
 50,
 1.3,
 0.7,
 '⚔️',
 '#9C27B0',
 1),
('STYLE_HYBRID',
 'Hybrid Wrestling',
 'Mix équilibré de tous les styles. Adaptable selon les talents et le public.',
 60,
 60,
 20,
 30,
 30,
 65,
 65,
 60,
 65,
 1.0,
 1.0,
 '🌐',
 '#607D8B',
 1),
('STYLE_FAMILY_FRIENDLY',
 'Family-Friendly',
 'Contenu tous publics, heroes vs villains clairs, messages positifs. Accessible aux enfants.',
 50,
 70,
 0,
 20,
 5,
 55,
 75,
 65,
 80,
 0.9,
 1.1,
 '👨‍👩‍👧‍👦',
 '#4CAF50',
 1),
('STYLE_INDIE',
 'Indie Wrestling',
 'Compétition pure, innovation, passion. Petit budget mais grande créativité.',
 75,
 50,
 15,
 40,
 40,
 80,
 55,
 50,
 60,
 1.2,
 0.9,
 '💎',
 '#00BCD4',
 1);

UPDATE Companies
SET CatchStyleId = 'STYLE_HYBRID'
WHERE CatchStyleId IS NULL;

COMMIT;
